development:
  adapter: postgresql
  database: boot_soccer
  host: localhost
  username: postgres
  password: postgres

test:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>