development:
  adapter: postgresql
  database: dj7kntnaj2qoh
  host: ec2-46-137-97-169.eu-west-1.compute.amazonaws.com
  username: wpeokgsgzzbstn
  password: d3336f9daa5dc1daf95070a8c016bbb53b51b9ab6042f40cf2ef1e5828aa63ce

test:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>