# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 772b59dd08ae716bb2499fc52c2e1f979455410e5d5bcc6a11be19ecb70d263f8b47edc35f56ff105e5f5aa1926e5ba5a5ac30bd220831e2eb7086b8002a6165
  twitter:
    api_key: ml0il7aua3ZRkpkeuQ3J6tm4u
    api_secret: DqHPMSdwA22mSaFgsghJQ0nxEGYHPsy4we5AXFOZfINtWvxX9C
    access_token: 888731416376352768-cGH99LigPgW3u6wx9O9e0eCwVuTGYQJ
    access_token_secret: pouw4AcfnV1BcZREv88BXFjwk2Z7aIwXBkPxXT8QYt1ug
test:
  secret_key_base: d04a79f3da87bc19451476882308ce5b9e0c3d0d11e3a286e32cc95ac0b58303d9db3f3a633a2c1a4dfbf1f095a71cbf5991fbdf2e0c0038107f7974a6ff1ae1
  twitter:
    api_key: ml0il7aua3ZRkpkeuQ3J6tm4u
    api_secret: DqHPMSdwA22mSaFgsghJQ0nxEGYHPsy4we5AXFOZfINtWvxX9C
    access_token: 888731416376352768-cGH99LigPgW3u6wx9O9e0eCwVuTGYQJ
    access_token_secret: pouw4AcfnV1BcZREv88BXFjwk2Z7aIwXBkPxXT8QYt1ug
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter:
    api_key: ml0il7aua3ZRkpkeuQ3J6tm4u
    api_secret: DqHPMSdwA22mSaFgsghJQ0nxEGYHPsy4we5AXFOZfINtWvxX9C
    access_token: 888731416376352768-cGH99LigPgW3u6wx9O9e0eCwVuTGYQJ
    access_token_secret: pouw4AcfnV1BcZREv88BXFjwk2Z7aIwXBkPxXT8QYt1ug
